version: '3'
services:
  app:
    build: .
    image: nexapay-bank-backend-image
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/nexapay
    networks:
      - app-network
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: nexapay
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge