version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: nexapay
    networks:
      - app-network
    ports:
      - "3306:3306"

  backend:
    build: .
    image: nexapay-bank-backend-image
    container_name: backend-container
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-container:3306/nexapay
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=root1234
    networks:
      - app-network
    ports:
      - "8082:8082"

networks:
  app-network:
    driver: bridge